### ISSUE TITLE
O link para o exemplo de uso de string está incorreto

### ISSUE THREAD

**Issue by leonardo-lemos** [elementary-br/the-vala-tutorial#32]
Em Tipos de dados -> String: o link para o exemplo de usos de string está errado, apontando para uma URL estranha vinda do GitBooks.

**Comment by naaando** [comment]
O problema é do próprio gitbook na verdade. Mas temos que achar um workaround de qualquer forma.

**Comment by robertsanseries** [comment]
Link não existe também no repositório original.

**Comment by robertsanseries** [comment]
Link e texto de referência ao exemplo de strings removido pois o mesmo não existe (nem no repositório original).
