### ISSUE TITLE
Link quebrado em Ferramentas -> vapigen

### ISSUE THREAD

**Issue by leonardo-lemos** [elementary-br/the-vala-tutorial#33]
O link para o 'Vala Bindings Tutorial' está quebrado.

**Comment by robertsanseries** [comment]
Link do projeto original também não existe:
https://github.com/valadate-project/the-vala-tutorial/blob/master/binding_libraries_with_vapi.md

Deve-se retirar o link? ou procurar um link na internet sobre o assunto?

**Comment by naaando** [comment]
@robertsanseries Por enquanto só comenta ele.

**Comment by robertsanseries** [comment]
Link removido. 

Commit  e00e17e9ed241138949ccf0969067dd0f4569faa
